### ISSUE TITLE
i18next.cloneInstance is not a function

### ISSUE THREAD

**Issue by newsiberian** [i18next/i18next-express-middleware#168]
Hi, after update `i18next` to 13.0.0 I've received this `TypeError: i18next.cloneInstance is not a function` error from [here](https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L19)

**Comment by jamuhl** [comment]
What did you pass to https://github.com/i18next/i18next-express-middleware#wire-up-i18next-to-request-object ?!?

`middleware.handle(i18next, {` must eventual be ` sure that is an instance?

**Comment by adrai** [comment]
probably you passed the return value of the `i18next.init()` function...
this is not possible anymore with v13 since the introduction of this: https://github.com/i18next/i18next/pull/1130
=> https://github.com/i18next/i18next/blob/master/CHANGELOG.md#1300
just pass `i18next` itself

**Comment by newsiberian** [comment]
Thank you. It works now
